# Generated by Django 5.0.4 on 2024-04-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_bground'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('food_img', models.ImageField(upload_to='foodimg')),
                ('food_desc', models.TextField()),
            ],
        ),
    ]
